language: ruby
rvm:
- 2.1.3
env:
  global:
    secure: WmmVhTF/IjMCwtzSmGtRSt+7tAarS8zaTg96FwNN1Z01PISrjS4SbrZEQeZcM5Q/UYs4lXA+zIqQlovSU6uHKhtmc/Avr2fFMeXbxAS78eqrIq+ku1X9XJLh5mBu7xwXab5XacU4vYmZ/AXKNrTeQ0gYGe01XEhTdhnhLbdPZnc=
deploy:
  provider: rubygems
  gem: factor-connector-ssh
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
