language: ruby
rvm:
- 2.1.3
env:
  global:
    secure: WmmVhTF/IjMCwtzSmGtRSt+7tAarS8zaTg96FwNN1Z01PISrjS4SbrZEQeZcM5Q/UYs4lXA+zIqQlovSU6uHKhtmc/Avr2fFMeXbxAS78eqrIq+ku1X9XJLh5mBu7xwXab5XacU4vYmZ/AXKNrTeQ0gYGe01XEhTdhnhLbdPZnc=
deploy:
  provider: rubygems
  gem: factor-connector-ssh
  api_key:
    secure: T24epDVon+Cx5yVd02i1ToHjr5pWnMjTCyudzlAXLBF9Rtsta6N6O41RNuHk94KXzoyfS4r8snblzENqR4OFYGE7VkDR1S14nE1rJWM7O9H3ExJh+mPrGtZNQ2Iaxl/a6wGNUb8TQYQEV8v+Qdt7FyFvtESZxHbSClJ7ChOZ1v0=
  on:
    tags: true
